FROM python:3.12-slim
WORKDIR /app
COPY requirements-registry.txt .
RUN pip install --no-cache-dir -r requirements-registry.txt
COPY registry ./registry
COPY registry_migrations ./registry_migrations
COPY registry-alembic.ini registry_app.py ./
EXPOSE 8001
CMD ["uvicorn", "registry_app:app", "--host", "0.0.0.0", "--port", "8001"]
