from typing import List, Dict, Any
from datetime import datetime, timedelta
import uuid

# Events list — populated in real-time by ANPR pipeline via add_event()
# No hardcoded fake data. Only real detections from live cameras will appear here.
EVENTS: List[Dict[str, Any]] = []
INCIDENTS: List[Dict[str, Any]] = []
TRAJECTORIES: Dict[str, List[Dict[str, Any]]] = {}
EVENT_TYPES = [
    {"id": "unauthorized_entry", "label": "Unauthorized Entry"},
    {"id": "loitering", "label": "Loitering"},
    {"id": "camera_obstruction", "label": "Camera Obstruction"},
    {"id": "object_removal", "label": "Object Removal"},
    {"id": "unattended_object", "label": "Unattended Object"},
    {"id": "after_hours_presence", "label": "After Hours Presence"},
]
import uuid
from datetime import datetime
from database import SessionLocal, DBEvent
from services.video_pipeline import embed_model
from websocket_manager import manager
import asyncio

def add_event(event: Dict[str, Any]):
    if isinstance(event.get("timestamp"), datetime):
        event["timestamp"] = event["timestamp"].isoformat()
    EVENTS.insert(0, event)
    
    # Broadcast to connected WebSocket clients
    try:
        loop = asyncio.get_event_loop()
        if loop.is_running():
            # Create a serializable copy of the event
            import copy
            ws_event = copy.deepcopy(event)
            if isinstance(ws_event.get("timestamp"), datetime):
                ws_event["timestamp"] = ws_event["timestamp"].isoformat()
            loop.create_task(manager.broadcast({"type": "new_event", "data": ws_event}))
    except Exception as e:
        print(f"WS error: {e}")
    
    # Store to PostgreSQL vector db
    text_to_embed = f"Event: {event['event_type']}. {event.get('description', '')} Location: {event.get('camera_name', '')}"
    
    embedding_vector = None
    if embed_model:
        embedding_vector = embed_model.encode(text_to_embed).tolist()

    try:
        db = SessionLocal()
        try:
            # Serialize datetime objects for JSON columns
            import copy
            safe_event = copy.deepcopy(event)
            if isinstance(safe_event.get("timestamp"), datetime):
                safe_event["timestamp"] = safe_event["timestamp"].isoformat()
                
            stored_timestamp = event.get("timestamp") or datetime.utcnow()
            if isinstance(stored_timestamp, str):
                try:
                    stored_timestamp = datetime.fromisoformat(stored_timestamp.replace("Z", "+00:00"))
                except ValueError:
                    stored_timestamp = datetime.utcnow()
            db_event = DBEvent(
                id=event["id"],
                camera_id=event["camera_id"],
                camera_name=event.get("camera_name", ""),
                timestamp=stored_timestamp,
                event_type=event["event_type"],
                severity=event["severity"],
                summary=event.get("description", ""),
                person_id=event.get("person_id"),
                clip_ref=event.get("clip_ref"),
                thumbnail=event.get("thumbnail"),
                embedding=embedding_vector,
                raw_data=safe_event
            )
            db.add(db_event)
            db.commit()
        except Exception as inner_e:
            db.rollback()
            raise inner_e
        finally:
            db.close()
    except Exception as e:
        print(f"Warning: Could not save event to the analytics database: {e}")
    if event.get("severity") in ["critical", "high"]:
        inc_id = f"INC_{uuid.uuid4().hex[:8].upper()}"
        INCIDENTS.insert(0, {
            "id": inc_id,
            "title": f"Escalated: {event['event_type'].replace('_', ' ').title()}",
            "summary": event.get("description", "Auto-escalated incident based on AI analysis."),
            "severity": event["severity"],
            "status": "open",
            "created_at": event["timestamp"],
            "event_ids": [event["id"]],
            "camera_ids": [event["camera_id"]],
            "person_ids": [event.get("person_id")] if event.get("person_id") else [],
            "timeline": [{
                "timestamp": event["timestamp"],
                "description": f"Event {event['id']} generated by {event['camera_id']} and auto-escalated."
            }]
        })
def get_events():
    return EVENTS
ZONES = {
    "entrance": {"label": "Entrance", "risk": "low", "color": "#10B981"},
    "cash_counter": {"label": "Cash Counter", "risk": "high", "color": "#F59E0B"},
    "atm": {"label": "ATM Zone", "risk": "medium", "color": "#6366F1"},
    "restricted": {"label": "Restricted Area", "risk": "critical", "color": "#EF4444"},
    "exterior": {"label": "Exterior / Parking", "risk": "low", "color": "#64748B"},
    "lobby": {"label": "Branch Lobby", "risk": "low", "color": "#0EA5E9"},
}
CAMERAS = [
    {"id": "CAM_01", "name": "Junction 4", "location": "SG Highway North", "zone": "intersection", "status": "active", "fps": 25, "resolution": "1080p", "rtsp": "rtsp://192.168.1.101:554/stream1"},
    {"id": "CAM_02", "name": "Highway A", "location": "SG Highway South", "zone": "highway", "status": "active", "fps": 30, "resolution": "1080p", "rtsp": "rtsp://192.168.1.102:554/stream1"},
    {"id": "CAM_03", "name": "Crosswalk B", "location": "CG Road", "zone": "pedestrian", "status": "active", "fps": 25, "resolution": "1080p", "rtsp": "rtsp://192.168.1.103:554/stream1"},
    {"id": "CAM_04", "name": "Junction 12", "location": "Ring Road", "zone": "intersection", "status": "active", "fps": 30, "resolution": "1080p", "rtsp": "rtsp://192.168.1.104:554/stream1"},
    {"id": "CAM_05", "name": "Alleyway", "location": "Old City", "zone": "restricted", "status": "active", "fps": 15, "resolution": "720p", "rtsp": "rtsp://192.168.1.105:554/stream1"},
    {"id": "CAM_06", "name": "Govt Building", "location": "Secretariat", "zone": "restricted", "status": "active", "fps": 30, "resolution": "4K", "rtsp": "rtsp://192.168.1.106:554/stream1"},
    {"id": "CAM_07", "name": "Highway B", "location": "Expressway Entry", "zone": "highway", "status": "warning", "fps": 15, "resolution": "720p", "rtsp": "rtsp://192.168.1.107:554/stream1"},
    {"id": "CAM_08", "name": "Public Square", "location": "Riverfront", "zone": "plaza", "status": "active", "fps": 15, "resolution": "1080p", "rtsp": "rtsp://192.168.1.108:554/stream1"},
]
def SYSTEM_STATS():
    # Attempt to fetch real hardware metrics
    cpu_percent = 0
    mem_percent = 0
    gpu_util = 0
    gpu_mem = 0
    
    try:
        import psutil
        cpu_percent = psutil.cpu_percent(interval=None)
        mem_percent = psutil.virtual_memory().percent
    except ImportError:
        pass
        
    try:
        import pynvml
        pynvml.nvmlInit()
        handle = pynvml.nvmlDeviceGetHandleByIndex(0)
        gpu_util = pynvml.nvmlDeviceGetUtilizationRates(handle).gpu
        mem_info = pynvml.nvmlDeviceGetMemoryInfo(handle)
        gpu_mem = round((mem_info.used / mem_info.total) * 100)
    except Exception:
        pass

    return {
        "cameras_online": sum(1 for c in CAMERAS if c["status"] == "active"),
        "cameras_warning": sum(1 for c in CAMERAS if c["status"] == "warning"),
        "cameras_offline": sum(1 for c in CAMERAS if c["status"] == "offline"),
        "events_today": len(EVENTS),
        "critical_events": sum(1 for e in EVENTS if e["severity"] == "critical"),
        "high_events": sum(1 for e in EVENTS if e["severity"] == "high"),
        "pending_review": sum(1 for e in EVENTS if e["status"] == "pending_review"),
        "active_incidents": len(INCIDENTS),
        "hardware": {
            "cpu": cpu_percent,
            "ram": mem_percent,
            "gpu_util": gpu_util,
            "gpu_mem": gpu_mem
        }
    }
# --- TOPOLOGY DATA ---
TOPOLOGY = {
    "floor_plan_url": "/blueprint.jpg",
    "cameras": [
        {"camera_id": "CAM_01", "x": 25, "y": 50}, # Entrance
        {"camera_id": "CAM_02", "x": 48, "y": 55}, # Cash Counter 1
        {"camera_id": "CAM_03", "x": 52, "y": 55}, # Cash Counter 2
        {"camera_id": "CAM_04", "x": 33, "y": 26}, # ATM Lobby
        {"camera_id": "CAM_05", "x": 68, "y": 26}, # Manager Cabin
        {"camera_id": "CAM_06", "x": 50, "y": 26}, # Vault Corridor
        {"camera_id": "CAM_07", "x": 68, "y": 75}, # Server Room
        {"camera_id": "CAM_08", "x": 10, "y": 50}, # Parking Lot
    ]
}
