"""Initial isolated registry schema, with PostGIS geometry on PostgreSQL."""
from alembic import op
import sqlalchemy as sa

revision = "0001_registry"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registry_vendors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('registry_api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vendor_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['registry_vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('digest')
    )
    op.create_index(op.f('ix_registry_api_keys_vendor_id'), 'registry_api_keys', ['vendor_id'], unique=False)
    op.create_table('registry_audit',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vendor_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['registry_vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registry_audit_resource_id'), 'registry_audit', ['resource_id'], unique=False)
    op.create_index(op.f('ix_registry_audit_vendor_id'), 'registry_audit', ['vendor_id'], unique=False)
    op.create_table('registry_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vendor_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('adapter', sa.String(length=30), nullable=False),
    sa.Column('connector_profile', sa.String(length=80), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_error', sa.String(length=60), nullable=True),
    sa.Column('last_sync_count', sa.Integer(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['registry_vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id', 'slug')
    )
    op.create_index(op.f('ix_registry_sources_department'), 'registry_sources', ['department'], unique=False)
    op.create_index(op.f('ix_registry_sources_vendor_id'), 'registry_sources', ['vendor_id'], unique=False)
    op.create_table('registry_cameras',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('discovered_name', sa.String(length=200), nullable=False),
    sa.Column('name_override', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_provenance', sa.String(length=500), nullable=True),
    sa.Column('camera_type', sa.String(length=80), nullable=True),
    sa.Column('ownership', sa.String(length=200), nullable=True),
    sa.Column('infrastructure', sa.JSON(), nullable=False),
    sa.Column('catalogue_status', sa.String(length=30), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_seen_in_catalogue_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.CheckConstraint('(latitude IS NULL AND longitude IS NULL) OR (latitude IS NOT NULL AND longitude IS NOT NULL)'),
    sa.CheckConstraint('latitude IS NULL OR (latitude >= -90 AND latitude <= 90)'),
    sa.CheckConstraint('longitude IS NULL OR (longitude >= -180 AND longitude <= 180)'),
    sa.ForeignKeyConstraint(['source_id'], ['registry_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id')
    )
    op.create_index(op.f('ix_registry_cameras_camera_type'), 'registry_cameras', ['camera_type'], unique=False)
    op.create_index('ix_registry_cameras_coordinates', 'registry_cameras', ['longitude', 'latitude'], unique=False)
    op.create_index(op.f('ix_registry_cameras_source_id'), 'registry_cameras', ['source_id'], unique=False)
    op.create_index('ix_registry_cameras_source_status', 'registry_cameras', ['source_id', 'catalogue_status'], unique=False)
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
        op.execute("ALTER TABLE registry_cameras ADD COLUMN geom geometry(Point,4326) GENERATED ALWAYS AS (CASE WHEN longitude IS NOT NULL AND latitude IS NOT NULL THEN ST_SetSRID(ST_MakePoint(longitude, latitude),4326) ELSE NULL END) STORED")
        op.execute("CREATE INDEX ix_registry_cameras_geom ON registry_cameras USING gist (geom)")


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_registry_cameras_source_status', table_name='registry_cameras')
    op.drop_index(op.f('ix_registry_cameras_source_id'), table_name='registry_cameras')
    op.drop_index('ix_registry_cameras_coordinates', table_name='registry_cameras')
    op.drop_index(op.f('ix_registry_cameras_camera_type'), table_name='registry_cameras')
    op.drop_table('registry_cameras')
    op.drop_index(op.f('ix_registry_sources_vendor_id'), table_name='registry_sources')
    op.drop_index(op.f('ix_registry_sources_department'), table_name='registry_sources')
    op.drop_table('registry_sources')
    op.drop_index(op.f('ix_registry_audit_vendor_id'), table_name='registry_audit')
    op.drop_index(op.f('ix_registry_audit_resource_id'), table_name='registry_audit')
    op.drop_table('registry_audit')
    op.drop_index(op.f('ix_registry_api_keys_vendor_id'), table_name='registry_api_keys')
    op.drop_table('registry_api_keys')
    op.drop_table('registry_vendors')
    # ### end Alembic commands ###
